# Generated by Django 6.0.6 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='anioNacimiento',
            field=models.IntegerField(default=2005),
            preserve_default=False,
        ),
    ]
