# Generated by Django 6.0.6 on 2026-06-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_estudiante_anionacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='anioNacimiento',
        ),
    ]
